"""empty message

Revision ID: 88130570cb72
Revises: def7ca5e5b0b
Create Date: 2025-01-10 21:23:20.192848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88130570cb72'
down_revision = 'def7ca5e5b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
